# Generated by Django 4.1.7 on 2023-04-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_seller", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="AProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=5)),
                ("description", models.CharField(max_length=50)),
                ("image", models.FileField(default="shaku", upload_to="media/")),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_seller.seller_user",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="product",
        ),
    ]
