# Generated by Django 4.1.7 on 2023-04-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_seller", "0003_aproduct_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aproduct",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
