# Generated by Django 4.1.7 on 2023-04-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_buyer", "0003_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="demo",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cart",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
