# Generated by Django 4.1.7 on 2023-04-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_buyer", "0004_cart_demo_cart_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="demo",
        ),
    ]
