# Generated by Django 4.1.7 on 2023-04-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_buyer", "0005_remove_cart_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub", models.CharField(max_length=25)),
                ("msg", models.CharField(max_length=200)),
                (
                    "conuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_buyer.user"
                    ),
                ),
            ],
        ),
    ]
