# Generated by Django 4.1.7 on 2023-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_buyer", "0006_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="conuser",
            field=models.EmailField(max_length=254),
        ),
    ]
