# Generated by Django 4.1.7 on 2023-05-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_buyer", "0007_alter_contact_conuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="reply",
            field=models.CharField(default=0, max_length=250),
        ),
    ]
