# Generated by Django 4.1.7 on 2023-05-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_buyer", "0008_contact_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="reply",
        ),
    ]
