# Generated by Django 4.2 on 2023-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_crud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
